### ISSUE TITLE
Typo of the 'extension' property in the Breakdown interface

### ISSUE THREAD

**Issue by FelicitiFriendlyFox** [dhershman1/phone-fns#14]
**Description**
The Typescript definitions incorrectly define the shape of the object returned by the breakdown function making the 'extension' property inaccessible by default.

**Comment by FelicitiFriendlyFox** [comment]
Submitted a PR with a fix: https://github.com/dhershman1/phone-fns/pull/15

**Comment by dhershman1** [comment]
Released with v4.0.2, thank you for the PR, sorry for the late reply this was buried under work notifications!
